# To enable this pre-commit hook run:
# `pip install pre-commit` or `brew install pre-commit`
# Then run `pre-commit install`

# Learn more about this config here: https://pre-commit.com/
default_language_version:
  python: python3.9

repos:
  - repo: local
    hooks:
      - id: make-lint-diff
        name: make lint-diff
        entry: bash -c 'git diff master -U0 | ./scripts/flake8-diff.sh'
        language: python
        additional_dependencies:
          - flake8

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
      - id: check-yaml
      # - id: end-of-file-fixer
      - id: requirements-txt-fixer
      - id: trailing-whitespace
        args:
          - --markdown-linebreak-ext=md

  - repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
      - id: black
        language_version: python3  # Should be a command that runs python3.6+
        args:
        - --diff
        - --skip-string-normalization

  - repo: https://github.com/codespell-project/codespell
    rev: v2.1.0
    hooks:
      - id: codespell  # See setup.cfg for args

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: 'v0.942'
    hooks:
      - id: mypy
        args:
          - --ignore-missing-imports
          - --scripts-are-modules
        additional_dependencies:
          - types-all

  - repo: https://github.com/asottile/pyupgrade
    rev: v2.31.1
    hooks:
      - id: pyupgrade
        args:
          - --py39-plus
          - --keep-runtime-typing
