name: python_tests
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    paths-ignore:
      - '.github/workflows/javascript_tests.yml'
      - 'vendor/js/**'
      - 'package*.json'
      - '**.js'
      - '**.vue'
      - '**.less'
      - '**.css'
jobs:
  python_tests:
    runs-on: ubuntu-18.04  # Should match Dockerfile.olbase, but had to be bumped as older version no longer supported
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - uses: actions/setup-python@v4
        with:
          python-version: 3.9
      - uses: actions/cache@v3
        with:
          path: ${{ env.pythonLocation }}
          key: ${{ runner.os }}-venv-${{ env.pythonLocation }}-${{ hashFiles('requirements*.txt') }}
      - name: Install dependencies
        run: |
          sudo apt-get update
          # https://lxml.de/installation.html#requirements
          sudo apt-get install libxml2-dev libxslt-dev
          pip install --upgrade pip setuptools wheel
          pip install -r requirements_test.txt
          pip list --outdated
      - run: make git
      - name: Run make i18n
        run: |
          make i18n
          make test-i18n
      - name: Run tests
        run: |
          git fetch --no-tags --prune --depth=1 origin master
          BASE_BRANCH="origin/master" make lint-diff
          make lint
          make test-py
          source scripts/run_doctests.sh
          mypy --install-types --non-interactive .
